<img src = 'images.jpeg' width = '400' height = '300' align = 'center'>

## Background 
In today's fast-paced business environment, the need for efficient and accurate reporting is paramount for informed decision-making. At Olist, a leading player in the Brazilian e-commerce landscape, one of the crucial tasks at hand is **automating** the generation of weekly revenue reports. Leveraging the rich insights provided by the Brazilian E-commerce Public dataset by "Olist," we aim to streamline this process and enhance operational efficiency.

The senior analystics team wants you to generate an automated weekly report to address the following questions:

Key Questions to Address in the Weekly Report:

* How much revenue did we make this week? By region?
* What was the w/w change in revenue?
* What was the y/y growth in revenue?
* What percentage of our sales target have we reached (QTD, and EoQ)?
* What are our average ratings for the week?
* What was the average time it took for an order to be fullfilled and delivered?

You can download the datasets for this walkthrough from the following site: 
https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce?select=olist_sellers_dataset.csv

## Objective:

Automate weekly reporting to provide comprehensive insights into Olist's performance, leveraging the Brazilian E-commerce Public dataset. Streamline reporting, enhance efficiency, and empower stakeholders with actionable insights.

## Goals:

1. **Automate weekly revenue reports** to streamline processes and reduce manual effort.
2. Provide accurate data on **revenue by region**, **week-over-week change**, **year-over-year growth**, and **sales target achievement**.
3. Deliver insights on **customer satisfaction** through weekly **average ratings**.
4. Evaluate **operational efficiency** by analyzing **order fulfillment** and **delivery times**.
5. Empower stakeholders with **actionable insights** to optimize strategies and drive **business growth**.


<div style="background-color:#f0f0f0; padding:10px; border-radius:5px;">
    <h2 style="color:#333333; text-align:center;">Executive Summary</h2>
    <p style="color:#555555; font-size:16px;">
        This week at Olist, our automated report, leveraging the Brazilian E-commerce Public dataset, indicates fluctuations in our performance metrics. This report provides an in-depth analysis of our weekly revenues, customer satisfaction, and operational efficiency.
    </p>
</div>

<div style="background-color:#f0f0f0; padding:10px; border-radius:5px;">
    <h3 style="color:#333333;">Key Performance Indicators</h3>
    <ul style="color:#555555;">
        <li>Weekly Revenue: This week, our total revenue amounted to <strong>$6,232.24</strong>.</li>
        <li>Revenue by Region: Details are segmented further in the attached detailed report.</li>
        <li>Week-over-Week Change: There was a slight decrease in revenue by <strong>-0.94%</strong>.</li>
        <li>Year-over-Year Growth: Revenue saw a decrease of <strong>-0.92%</strong> compared to the same week last year.</li>
        <li>Sales Target Achievement:
            <ul>
                <li>Quarter-to-Date (QTD): Achieved <strong>135.92%</strong> of the target.</li>
                <li>End of Quarter (EoQ): Currently at <strong>95.59%</strong> of the target.</li>
            </ul>
        </li>
    </ul>
</div>

<div style="background-color:#f0f0f0; padding:10px; border-radius:5px;">
    <h3 style="color:#333333;">Customer Satisfaction</h3>
    <ul style="color:#555555;">
        <li>Average Customer Ratings: This week, the average customer rating was <strong>4.31</strong>, indicating satisfactory but not excellent performance.</li>
        <li>Order Fulfillment and Delivery:
            <ul>
                <li>Orders Fulfilled: A total of <strong>72 orders</strong> were processed this week.</li>
                <li>Average Delivery Time: The average delivery time was <strong>3.73 days</strong>, indicating a need for improvement in delivery efficiency.</li>
            </ul>
        </li>
    </ul>
</div>

<div style="background-color:#f0f0f0; padding:10px; border-radius:5px;">
    <h3 style="color:#333333;">Strategic Recommendations</h3>
    <ol style="color:#555555;">
        <li>Enhance Delivery Efficiency: Focus on reducing the average delivery time to improve customer satisfaction and repeat business.</li>
        <li>Monitor Revenue Fluctuations: Investigate the causes of week-over-week and year-over-year declines in revenue and address them strategically.</li>
        <li>Capitalize on High QTD Achievement: Leverage the momentum from exceeding QTD sales targets to ensure strong closure by the end of the quarter.</li>
    </ol>
</div>

<div style="background-color:#f0f0f0; padding:10px; border-radius:5px;">
    <h3 style="color:#333333;">Conclusion</h3>
    <p style="color:#555555; font-size:16px;">
        In conclusion, while we are performing well against our sales targets, there are areas for improvement in customer satisfaction and delivery times. By addressing these issues, we can improve our service quality and sustain our revenue growth.
    </p>
</div>

<div style="background-color:#f0f0f0; padding:10px; border-radius:5px;">
    <h3 style="color:#333333;">Next Steps</h3>
    <ul style="color:#555555;">
        <li>Data-Driven Strategy Adjustment: Use the insights from this report to refine our strategies, focusing on weak areas and bolstering our strengths.</li>
        <li>Continuous Monitoring: Keep a close watch on the weekly performance metrics to adapt quickly to any significant changes.</li>
    </ul>
    <p style="color:#555555; font-size:16px;">
        <strong>Note:</strong> For detailed revenue analysis by region and further insights, refer to the full report attached.
    </p>
</div>

<div style="background-color:#f0f0f0; padding:10px; border-radius:5px;">
    <h3 style="color:#333333;">Data Source</h3>
    <p style="color:#555555; font-size:16px;">
        Data used for this report is sourced from the <strong>Brazilian E-commerce Public dataset by Olist</strong> available at: <a href="https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce?select=olist_sellers_dataset.csv" style="color:#007bff; text-decoration:underline;">Kaggle Olist Dataset</a>.
    </p>
</div>


In [1]:
# Imports
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import pandasql as ps

In [2]:
# Reading the data
customers_df = pd.read_csv('olist_customers_dataset.csv')
order_items_df = pd.read_csv('olist_order_items_dataset.csv')
payments_df = pd.read_csv('olist_order_payments_dataset.csv')
reviews_df = pd.read_csv('olist_order_reviews_dataset.csv')
orders_df = pd.read_csv('olist_orders_dataset.csv')
products_df = pd.read_csv('olist_products_dataset.csv')
sellers_df = pd.read_csv('olist_sellers_dataset.csv')
product_category_df = pd.read_csv('product_category_name_translation.csv')

In [3]:
# Example run of SQL in jupyter:

q = """SELECT * FROM customers_df LIMIT 5"""

ps.sqldf(q, locals())

customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0   
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3   
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e   
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c   
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066   

   customer_zip_code_prefix          customer_city customer_state  
0                     14409                 franca             SP  
1                      9790  sao bernardo do campo             SP  
2                      1151              sao paulo             SP  
3                      8775        mogi das cruzes             SP  
4                     13056               campinas             SP

**What do we want in our dataset?** (Refer Schema on Kaggle)

Customers
* customer_id
* customer_unqiue_id
* customer_zip_code
* customer_city
* customer_state

Order Item
* order_id
* order_item_id
* product_id
* seller_id
* shipping_limit_date
* price


Reviews
* review_id
* order_id
* review_score

Orders
* order_id
* customer_id
* order_status
* order_purchase_time
* order_approved_at
* order_delivered_carrier_date
* order_delivered_customer_date

Products
* product_id
* product_category


Sellers
* seller_id
* seller_zip_code_prefix
* seller_city
* seller_state

Product Category
* product_category
* product_category_name_english

In [4]:
# Our primary Table:
q1 = """SELECT 
            c.customer_id,
            customer_unique_id,
            customer_zip_code_prefix,
            customer_city,
            customer_state,
            
            oi.order_id,
            oi.product_id,
            oi.seller_id,
            shipping_limit_date,
            price,
            
            review_id,
            review_score,
            
            order_status,
            order_purchase_timestamp,
            order_approved_at,
            order_delivered_carrier_date,
            order_delivered_customer_date,
            
            
            seller_zip_code_prefix,
            seller_city,
            seller_state,
            
            product_category_name_english,
            
            payment_type

            
            
            
            FROM 
            order_items_df as oi
            inner join
            orders_df as o 
            on o.order_id = oi.order_id
            inner join
            customers_df as c
            on o.customer_id = c.customer_id            
            inner join
            reviews_df as r 
            on r.order_id = o.order_id
            inner join
            products_df as p
            on p.product_id=oi.product_id
            inner join 
            sellers_df as s
            on s.seller_id = oi.seller_id
            inner join product_category_df as pc 
            on pc.product_category_name = p.product_category_name
            inner join payments_df as pm
            on pm.order_id = oi.order_id
            group by 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
            """
df=ps.sqldf(q1, locals())


In [5]:
df.head(10)

customer_id                customer_unique_id  \
0  00012a2ce6f8dcda20d059ce98491703  248ffe10d632bebe4f7267f1f44844c9   
1  000161a058600d5901f007fab4c27140  b0015e09bb4b6e47c52844fab5fb6638   
2  0001fd6190edaaf884bcaf3d49edf079  94b11d37cd61cb2994a194d11f89682b   
3  0002414f95344307404f0ace7a26f1d5  4893ad4ea28b2c5b3ddf4e82e79db9e6   
4  000379cdec625522490c315e70c7a9fb  0b83f73b19c2019e182fd552c048a22c   
5  0004164d20a9e969af783496f3408652  104bdb7e6a6cdceaa88c3ea5fa6b2b93   
6  000419c5494106c306a97b5635748086  14843983d4a159080f6afe4b7f346e7c   
7  00046a560d407e99b969756e0b10f282  0b5295fc9819d831f68eb0e9a3e13ab7   
8  00050bf6e01e69d5c0fd612f1bcfb69c  e3cf594a99e810f58af53ed4820f25e5   
9  000598caf2ef4117407665ac33275130  7e0516b486e92ed3f3afdd6d1276cfbd   

   customer_zip_code_prefix   customer_city customer_state  \
0                      6273          osasco             SP   
1                     35550     itapecerica             MG   
2                     29830    nova venecia             ES   
3                     39664        mendonca             MG   
4                      4841       sao paulo             SP   
5                     13272        valinhos             SP   
6                     24220         niteroi             RJ   
7                     20540  rio de janeiro             RJ   
8                     98700            ijui             RS   
9                     35540        oliveira             MG   

                           order_id                        product_id  \
0  5f79b5b0931d63f1a42989eb65b9da6e  64315bd8c0c47303179dd2e25b579d00   
1  a44895d095d7e0702b6a162fa2dbeced  84183944dc7cddca87a5d384452c1d3c   
2  316a104623542e4d75189bb372bc5f8d  9df2b21ec85378d71df4404712e17478   
3  5825ce2e88d5346438686b0bba99e5ee  af3ec22cce878225aae6d9eb6c7a78eb   
4  0ab7fb08086d4af9141453c91878ed7a  868b3136c5b206f91b8208fbfdf2cb7c   
5  cd3558a10d854487b4f907e9b326a4fc  fa23bf270fb9880690b07d09b9f9ff20   
6  07f6c3baf9ac86865b60f640c4f923c6  daa7499d1e545811c843e8189cd30286   
7  8c3d752c5c02227878fae49aeaddbfd7  ba9f160a6ae1c23f25d690fd06fe4fd8   
8  fa906f338cee30a984d0945b3832e431  79ad39409fa4bcc36b4b7f734c79c2a2   
9  9b961b894e797f63622137ff7eb1c1af  c53feca3e876804031ed4a4b48ac8f1e   

                          seller_id  shipping_limit_date    price  \
0  7aa4334be125fcdd2ba64b3180029f14  2017-11-21 16:35:32    89.80   
1  2a1348e9addc1af5aaa619b1a3679d6b  2017-07-20 09:55:12    54.90   
2  46dc3b2cc0980fb8ec44634e21d2718e  2017-03-06 11:15:20   179.99   
3  aafe36600ce604f205b86b5084d3d767  2017-08-23 03:10:27   149.90   
4  4a3ca9315b744ce9f8e9374361493884  2018-04-10 03:10:19    93.00   
5  1b8356dabde1d35e17cef975c3f82730  2017-04-18 08:50:12    59.99   
6  e5a3438891c0bfdb9394643f95273d8e  2018-03-08 14:10:38    34.30   
7  ac3508719a1d8f5b7614b798f70af136  2017-12-22 12:45:31   120.90   
8  1da3aeb70d7989d1e6d9b0e887f97c23  2017-09-21 16:15:13    69.99   
9  6c6cc59a5c00cacc5054ca06d65cc282  2018-08-21 12:25:08  1107.00   

                          review_id  review_score order_status  \
0  65645c124061b43b2edc38b05ee76aab             1    delivered   
1  862cae301754fcafa8129022c8eca937             4    delivered   
2  238e7cc8c4579a3d4db8f2a211db5b06             5    delivered   
3  c3a9be1f602ecba1c7bdff5639c975fe             5    delivered   
4  fab6aa1b4c382a27ae8625faa342c229             4    delivered   
5  2bf2913f793ffd3739c41cccfc43c8c5             1    delivered   
6  f72dc5627bd78fb840c136295ae345f5             1    delivered   
7  494c3989426b2271e20bbac41e6acf96             5    delivered   
8  d50791ccc55c7f5ff8fde67e7c3baf59             5    delivered   
9  f149a8ca142b2324fd2578f67eaacd4b             5    delivered   

  order_purchase_timestamp    order_approved_at order_delivered_carrier_date  \
0      2017-11-14 16:08:26  2017-11-14 16:35:32          2017-11-17 15:32:08   
1      2017-07-16 09:40:32  2017-07-16 09:55:12          2017-07-19 19:09:37   
2     

In [6]:
# Basic Overview:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100750 entries, 0 to 100749
Data columns (total 22 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   customer_id                    100750 non-null  object 
 1   customer_unique_id             100750 non-null  object 
 2   customer_zip_code_prefix       100750 non-null  int64  
 3   customer_city                  100750 non-null  object 
 4   customer_state                 100750 non-null  object 
 5   order_id                       100750 non-null  object 
 6   product_id                     100750 non-null  object 
 7   seller_id                      100750 non-null  object 
 8   shipping_limit_date            100750 non-null  object 
 9   price                          100750 non-null  float64
 10  review_id                      100750 non-null  object 
 11  review_score                   100750 non-null  int64  
 12  order_status                  

In [7]:
# Decriptive Overall Stats:
df.describe(include = 'all')

customer_id                customer_unique_id  \
count                             100750                            100750   
unique                             96516                             93396   
top     be1c4e52bb71e0c54b11a26b8e8d59f2  8d50f5eadf50201ccdcedfb9e2ac8455   
freq                                  12                                15   
mean                                 NaN                               NaN   
std                                  NaN                               NaN   
min                                  NaN                               NaN   
25%                                  NaN                               NaN   
50%                                  NaN                               NaN   
75%                                  NaN                               NaN   
max                                  NaN                               NaN   

        customer_zip_code_prefix customer_city customer_state  \
count              100750.000000        100750         100750   
unique                       NaN          4093             27   
top                          NaN     sao paulo             SP   
freq                         NaN         15802          42402   
mean                35110.153896           NaN            NaN   
std                 29805.617127           NaN            NaN   
min                  1003.000000           NaN            NaN   
25%                 11320.000000           NaN            NaN   
50%                 24360.000000           NaN            NaN   
75%                 58840.000000           NaN            NaN   
max                 99980.000000           NaN            NaN   

                                order_id                        product_id  \
count                             100750                            100750   
unique                             96516                             32171   
top     5a3b1c29a49756e75f1ef513383c0c12  99a4788cb24856965c36a24e339b6058   
freq                                  12                               461   
mean                                 NaN                               NaN   
std                                  NaN                               NaN   
min                                  NaN                               NaN   
25%                                  NaN                               NaN   
50%                                  NaN                               NaN   
75%                                  NaN                               NaN   
max                                  NaN                               NaN   

                               seller_id  shipping_limit_date          price  \
count                             100750               100750  100750.000000   
unique                              3028                91386            NaN   
top     6560211a19b47992c3666cc44a7e94c0  2017-10-24 13:06:21            NaN   
freq                                1969                   12            NaN   
mean                                 NaN                  NaN     124.161214   
std                                  NaN                  NaN     186.968926   
min                                  NaN                  NaN       0.850000   
25%                                  NaN                  NaN      40.000000   
50%                                  NaN                  NaN      78.000000   
75%                                  NaN                  NaN     139.000000   
max                                  NaN                  NaN    6735.000000   

                               review_id   review_score order_status  \
count                             100750  100750.000000       100750   
unique                             96319            NaN            7   
top     b8017a9ca639f71a9a4a745985f4a729            NaN    delivered   
freq                                   8            NaN        98664   
mean                                 NaN       4.0790

In [8]:
#Decscriptive Numeric Stats
df.describe()

customer_zip_code_prefix          price   review_score  \
count             100750.000000  100750.000000  100750.000000   
mean               35110.153896     124.161214       4.079007   
std                29805.617127     186.968926       1.351646   
min                 1003.000000       0.850000       1.000000   
25%                11320.000000      40.000000       4.000000   
50%                24360.000000      78.000000       5.000000   
75%                58840.000000     139.000000       5.000000   
max                99980.000000    6735.000000       5.000000   

       seller_zip_code_prefix  
count           100750.000000  
mean             24642.947782  
std              27695.524335  
min               1001.000000  
25%               6429.000000  
50%              13690.000000  
75%              29156.000000  
max              99730.000000

In [9]:
#Change the type of zip code and seller zip code

df.customer_zip_code_prefix=df.customer_zip_code_prefix.astype(str)
df.seller_zip_code_prefix=df.seller_zip_code_prefix.astype(str)

In [10]:
#Shape of our dataframe
print(df.shape)

(100750, 22)


In [11]:
#Columns in our dataframe
df.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'order_id', 'product_id',
       'seller_id', 'shipping_limit_date', 'price', 'review_id',
       'review_score', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'seller_zip_code_prefix',
       'seller_city', 'seller_state', 'product_category_name_english',
       'payment_type'],
      dtype='object')

In [12]:
# Dataframe for Nulls and their percentage in column 
nulls = pd.DataFrame(df.isnull().sum()/df.shape[0]*100, columns = ['perecntage_nulls'])
nulls['total_nulls'] = df.isnull().sum()
nulls


perecntage_nulls  total_nulls
customer_id                            0.000000            0
customer_unique_id                     0.000000            0
customer_zip_code_prefix               0.000000            0
customer_city                          0.000000            0
customer_state                         0.000000            0
order_id                               0.000000            0
product_id                             0.000000            0
seller_id                              0.000000            0
shipping_limit_date                    0.000000            0
price                                  0.000000            0
review_id                              0.000000            0
review_score                           0.000000            0
order_status                           0.000000            0
order_purchase_timestamp               0.000000            0
order_approved_at                      0.012903           13
order_delivered_carrier_date           0.976675          984
order_delivered_customer_date          2.071464         2087
seller_zip_code_prefix                 0.000000            0
seller_city                            0.000000            0
seller_state                           0.000000            0
product_category_name_english          0.000000            0
payment_type                           0.000000            0

### Assessing missing values in `order_approved_at`

In [13]:
q = """SELECT * FROM df WHERE order_approved_at IS NULL"""

ps.sqldf(q, locals())

customer_id                customer_unique_id  \
0   07a2a7e0f63fd8cb757ed77d4245623c  79af1bbf230a2630487975aa5d7d6220   
1   0bf35cac6cc7327065da879e2d90fae8  c4c0011e639bdbcf26059ddc38bd3c18   
2   1e101e0daffaddce8159d25a8e53f2b2  c8822fce1d0bfa7ddf0da24fff947172   
3   2127dc6603ac33544953ef05ec155771  8a9a08c7ca8900a200d83cf838a07e0b   
4   29c35fc91fc13fb5073c8f30505d860d  7e1a5ca61b572d76b64b6688b9f96473   
5   4c1ccc74e00993733742a3c786dc3c1f  91efb7fcabc17925099dced52435837f   
6   684cb238dc5b5d6366244e0e0776b450  6ff8b0d7b35d5c945633b8d60165691b   
7   68d081753ad4fe22fc4d410a9eb1ca01  2e0a2166aa23da2472c6a60c4af6f7a6   
8   74bebaf46603f9340e3b50c6b086f992  f79be7c08dd24b72d34634f1b89333a4   
9   a3d3c38e58b9d2dfb9207cab690b6310  5a4fa4919cbf2b049e72be460a380e5b   
10  d5de688c321096d15508faae67a27051  d49f3dae6bad25d05160fc17aca5942d   
11  d85919cb3c0529589c6fa617f5f43281  c094ac95fcd52f821809ec232a7a6956   
12  f67cd1a215aae2a1074638bbd35a223a  bc1896dc77f49e6dec880445a9b443a3   

   customer_zip_code_prefix         customer_city customer_state  \
0                     37660          paraisopolis             MG   
1                     13225       varzea paulista             SP   
2                     27945                 macae             RJ   
3                      6708                 cotia             SP   
4                     62700               caninde             CE   
5                     93548         novo hamburgo             RS   
6                     11030                santos             SP   
7                      3573             sao paulo             SP   
8                     65110   sao jose de ribamar             MA   
9                     35620                abaete             MG   
10                    36400  conselheiro lafaiete             MG   
11                    95795         sao vendelino             RS   
12                    21020        rio de janeiro             RJ   

                            order_id                        product_id  \
0   51eb2eebd5d76a24625b31c33dd41449  7868a64aa111bbb4f41f8e1146c0becb   
1   d77031d6a3c8a52f019764e68f211c69  02a79d79e818ad0be36cfc843a6af7ad   
2   12a95a3c06dbaec84bcfb0e2da5d228a  c6dd917a0be2a704582055949915ab32   
3   e04abd8149ef81b95221e88f6ed9ab6a  0e20a07ca1714df21f9b07ca3bf7c682   
4   5cf925b116421afa85ee25e99b4c34fb  c6dd917a0be2a704582055949915ab32   
5   8a9adc69528e1001fc68dd0aaebbb54a  2c2b6a28924791234bd386bddb17512e   
6   c1d4211b3dae76144deccd6c74144a88  5ab02ca028398131a5ae91401eb49788   
7   d69e5d356402adc8cf17e08b5033acfb  cae2e38942c8489d9d7a87a3f525c06b   
8   2babbb4b15e6d2dfe95e2de765c97bce  c6dd917a0be2a704582055949915ab32   
9   2eecb0d85f281280f79fa00f9cec1a95  4fd676d9c4723d475026e40aeae56957   
10  7002a78c79c519ac54022d4f8a65e6e8  c3b271f47e73d0c9ccf1b43b7606c705   
11  3c0b8706b065f9919d0505d3b3343881  db8ed3d08891d16a2438a67ab3acb740   
12  88083e8f64d95b932164187484d90212  8c5876b1c7768217964f353bc7e64393   

                           seller_id  shipping_limit_date   price  \
0   cca3071e3e9bb7d12640c9fbe2301306  2017-02-28 14:52:27   59.90   
1   cb3dd9ce66268c7a3ca7241ac70ab58c  2017-02-25 10:04:19   28.99   
2   7a67c85e85bb2ce8582c35f2203ad736  2017-02-21 12:05:55   79.99   
3   4e7c18b98d84e05cbae3ff0ff03846c2  2017-02-22 13:40:00  309.90   
4   7a67c85e85bb2ce8582c35f2203ad736  2017-02-22 15:48:35   79.99   
5   a4b6b9b992b46e9ef863637af96e04bc  2017-02-22 11:45:31  379.00   
6   80e6699fe29150b372a0c8a1ebf7dcc8  2017-01-23 12:48:08   39.99   
7   cca3071e3e9bb7d12640c9fbe2301306  2017-02-26 01:28:47  149.80   
8   7a67c85e85bb2ce8582c35f2203ad736  2017-02-22 16:15:03   79.99   
9   5fd924b4836098a5be0ecf81ba054ce0  2017-02-21 16:21:55  135.00   
10  cca3071e3e9bb7d12640c9fbe2301306  2017-01-29 22:26:59   45.90   
11  004c9cd9d87a3c30c522c48c4fc07416  2017-02-22 14:53:27  133.99   
12  0db783cfcd3b73998abc6e10e59a102f  2017-02-22 21:49:19   49.00   

                           revi

**Observations**:
It seems the missing values are assocaited with `2017-02-18`. We will check if this is consistent across the data set.

In [14]:
q = """

SELECT 
    *
FROM df
WHERE order_purchase_timestamp LIKE '%2017-02-18%'

"""
ps.sqldf(q, locals())

customer_id                customer_unique_id  \
0   01391e5f325943c1d9dee9e6202aa7e5  99aba93205c163f13fda5babda17e6c5   
1   05775243ed704519f900b91f95b9593a  73daee815cdbdeacecd0f29b04436cab   
2   07a2a7e0f63fd8cb757ed77d4245623c  79af1bbf230a2630487975aa5d7d6220   
3   0b530e0541b196e2873192ff6cd44dae  b0276fd6017b7395aa781016653a087b   
4   0bf35cac6cc7327065da879e2d90fae8  c4c0011e639bdbcf26059ddc38bd3c18   
5   0f07fc4aa37cf3ef826d1a14883847f9  0eaff0480bd972db84cf247671da4130   
6   101761ee49f83d5aedd8e7b2cb007363  ce6615af482d0efa24602ebc67fbfc9e   
7   12d53177e4683bebc84096c140330369  f8a45c354372724b0217757b40c245bd   
8   1bfb55c78f90699dcb61d9622cafd180  9dc4b05ce1cabbd9c3be75b2420d4d87   
9   1eda56b47988d592fec945da9ee88c56  551a43d7e0bb14426e6ca28d7eec8463   
10  2127dc6603ac33544953ef05ec155771  8a9a08c7ca8900a200d83cf838a07e0b   
11  2469cf22e7ce32bfe501b0e3860e2a10  532e9c4eb21f0aca2f994f5037594206   
12  27a9cbe94e6fe0574f9b16c5ece47fd4  2ce92c0d3ec4a2fef1b4503f79b53cc2   
13  29c35fc91fc13fb5073c8f30505d860d  7e1a5ca61b572d76b64b6688b9f96473   
14  2dd14748e5c894ea5994aa40aa4fc77b  28650ae59f91b5215b7ac85371600caa   
15  2dd14748e5c894ea5994aa40aa4fc77b  28650ae59f91b5215b7ac85371600caa   
16  2f97b02d40643e010692dda69192260f  efd301af5468c61de8de3f0c85d9a8bb   
17  3bfc56d74bd9034653df36bb0de5cdf0  01b0d417af24703a0b20cbe71f354285   
18  3d455fb7aa499fd0cea2a2306b4c43ad  c0779cfb3d6695eb9a6c14772852e10e   
19  44624c889935b95b1b070efaa459de42  c0779cfb3d6695eb9a6c14772852e10e   
20  460137bbe214bff87bb79f1c0aa1de66  c62ccb7adc9ea2a094c7c8eabb03442d   
21  48c75023334a516ed72d8dfb615be9d2  739f7b409586922461ba4fb82369eec1   
22  4c1ccc74e00993733742a3c786dc3c1f  91efb7fcabc17925099dced52435837f   
23  4db09730e85cacf07aa9c7ce98ee2a16  67d17914ab163a6ad72efd3a37a54cea   
24  4e798bde1c7399fbb0763d0f35d9af07  ebbf4018130a768f1d9e632f8d5541b9   
25  536ab83be11994431d8e0686d65e481f  579e8646725311074b0d0e7af5f220ce   
26  5679bf4d0900a0e28ce699536c8c3e43  c400a61d8b936f7d10930fc142a39407   
27  5679bf4d0900a0e28ce699536c8c3e43  c400a61d8b936f7d10930fc142a39407   
28  60455200cb4beb4dbd68d4a390f472a5  2526d3bb06624f7c5bedf2ef7a5bc4f0   
29  60714f8c3737c4bd4b745de1fb196514  baec81c668e3e2869bae58beb48b433d   
30  627ed432c94cb78c7372b6f7cade43b5  736f5dd51ba596512ab19214081058a6   
31  6cf4840b6dfe102270032fca98880fc2  f38d0a168948a5dd98c2b8e0f9eb3120   
32  7454f64a4378ab4a3aacafdef6a1feeb  c400a61d8b936f7d10930fc142a39407   
33  7454f64a4378ab4a3aacafdef6a1feeb  c400a61d8b936f7d10930fc142a39407   
34  74bebaf46603f9340e3b50c6b086f992  f79be7c08dd24b72d34634f1b89333a4   
35  80daa5cf717bc359cab1de3b48034771  024ab36a6207906cf0d2767466419017   
36  85f5620057716466350882996fba5069  9b63fecadb7d20796f519cabfb9a9e2d   
37  8b94ba786c5a6e3e2ffa2fb353903c53  1c4aa8de4fc95722dfd26f9b5050fee8   
38  a7de58749b09c1b70e10847d7f8a3986  af3afb557b92d4b738662b63bd68f894   
39  ab6cc37c6e78c5c1c7314592c14a5cdb  c128f517bff061b450b5604a3478e1a6   
40  abbd729eb82f54309a051a9a003bb6a1  13938bb4237e9544d3c945a055adb308   
41  b1161707c5b3711b7cf6213c114c91b2  650dd69e8e20391188d727da3599e9a7   
42  b3194c3f6631231daa204fb5c759c53f  620b7e6275faee4da2d637e42dc30aaa   
43  b73ac6c93755e492832020b47ded906f  a7756cfdda50719fed15a09df71e081b   
44  bffec816107aa26f6836f6fa687c9039  9060b6b1f3023237c45bf25aba446795   
45  c112cbf7b38f4c1df8d307ac2f71c07e  eba2e542b6a37aae711332ae396a6902   
46  c18796182709c0d37ce5bc1d46c79ca6  0dced00907d6b96a2662a6746a9372dc   
47  e4142014a0a938c8b826a6c1cecdd46c  17f5f0bf8f88906f32ce44c5f564cb49   
48  e5b4c35110318298cc63deff9c26c169  60247426854cfcb908159accf11109f2   
49  f67cd1a215aae2a1074638bbd35a223a  bc1896dc77f49e6dec880445a9b443a3   
50  f7cbc5b5009187e1d0983e1ff7a5c6c2  0b20a59951e8914258511b01d9bfaad4   
51  feef2d3e0adf31da426b071891551813  35cac0573a06f610cc8e356e0710d9b1   
52  feef2d3e0adf31da426b071891551813  35cac0573a06f610cc8e356e0710d9b1   

   customer_zip_code_prefix 

**Observation**:
- The missing values dont seem to be associated with the date 2017-02-18.
- The values might be simply missing at random

We can do a check to see if the orders approved have been delivered and the type of payment associated with it

In [15]:
q = """
SELECT 
    order_purchase_timestamp,
    order_approved_at,
    order_status,
    payment_type
FROM df
WHERE order_approved_at IS NULL and order_status = 'delivered'
    
"""
ps.sqldf(q, locals())

order_purchase_timestamp order_approved_at order_status payment_type
0       2017-02-18 15:52:27              None    delivered       boleto
1       2017-02-18 11:04:19              None    delivered       boleto
2       2017-02-17 13:05:55              None    delivered       boleto
3       2017-02-18 14:40:00              None    delivered       boleto
4       2017-02-18 16:48:35              None    delivered       boleto
5       2017-02-18 12:45:31              None    delivered       boleto
6       2017-01-19 12:48:08              None    delivered       boleto
7       2017-02-19 01:28:47              None    delivered       boleto
8       2017-02-18 17:15:03              None    delivered       boleto
9       2017-02-17 17:21:55              None    delivered       boleto
10      2017-01-19 22:26:59              None    delivered       boleto
11      2017-02-17 15:53:27              None    delivered       boleto
12      2017-02-18 22:49:19              None    delivered       boleto

**Observation**:
- As we can see from the table above, the missing values are associated with the payment_type `boleto` 
- We thereby can conclude the `order_approved_at` values not missing at random but are associated with the payment_type
- We need to further investigate if there are issues with this payment type 

### Assessing missing values in `order_delivered_carrier_date`:

In [16]:
q = """

SELECT
    *
FROM df
WHERE order_delivered_carrier_date IS NULL
"""
ps.sqldf(q, locals())

customer_id                customer_unique_id  \
0    002348c1099e3229276c8ad7d4ddc702  934c19eeef04da89928f995df85cf3f8   
1    00f8a4bbb515bfe8f84f9cfa45621250  b2bb87ebda9c0aad99e72716de580b63   
2    01866d949d55c81c28d255114948b72b  7ce5c1a457d7d23a2fca222d8f3d37e3   
3    01950e4d4d0f0f8561e721ad5c8b0f9a  9de756cc22c1ff1352e519c5e8ea206e   
4    019f5bb93ed18dd059051c3f81abe394  e374cc2cc1cb40c3dd3bc070a13665f0   
5    01f7b7a4e25cda9ce48c0f7263f7452d  e55fbf4f9ca883b98aeaa2b149987027   
6    021e3ddcc0581de5bf087b1d87e4b136  3fb1672507c668998549f7c91cbe932b   
7    021e84751ba0ead75b6d314a6ead88d9  9a58c55c10b4eb6c69fb0874d8beb466   
8    0228874050786ca37c963d514a71684d  f475dc24f1a2e37576b20e8c23970543   
9    024c5e8dc02a1cd8856a7f257bd98844  de25b230e97531bd3c3890ed4f01a607   
10   028605cdb42f4bb9653d81ce3116f2ae  b2e75c0edc785fd8cb4c5b264fc7793c   
11   033f5ddbb536a477e81abd786f23f452  77990aebc36116f217b324ac96d6ad10   
12   0340b2de09f18a986fea9f26cc7b2d9c  57668c60f87bc896997917dace48bcac   
13   03a6f3a3935165f5d26f4797ba6039bb  94c1c602b16a9fdfbc154ef63cfa50f9   
14   03eaeeab9883ef63043d7f0e0325a370  93d9e516a351a7747fc9830ae9525062   
15   0447d86a923f286dcdecab2c0240722a  788d35a7b2d874b34779c8af1e0f23ef   
16   046898f5066f7287e47eda8a80c80a56  b82cc08ec7069053a3f5219ec59d3497   
17   0496b71ebc90246e3e2ed28846651580  6a1ff37aa020ee71c9e359413e553826   
18   04d7d73089b39d83f81b829cbd98e43d  86badf62319a7671b78a73b6b1e69fbf   
19   0504a5d74832ef83b263972cc39d7377  baebfe959a654aa97bd3e0b179a31c3c   
20   0581d4ef9081dc26ed2e1580a6e34ea3  2587940c36e40620fb5384f80d56bdb2   
21   05ef118f93c526baee95865084ed4ab1  02fd7a082b1184535bd4eefd87543519   
22   065e2905f7a83f066d3e66ceb70cdf20  b7f6cea0a497e31650f4596c5e5c0eac   
23   066bab10d1281abb5baefa5d7772cce0  f8ac33ce25aad89ade14c52fac3cc452   
24   066bab10d1281abb5baefa5d7772cce0  f8ac33ce25aad89ade14c52fac3cc452   
25   0739e05c71a6246747cddc1af25fcce8  036a1e754cf00a7c7f1ea31bc6d93149   
26   077df306cf5b17588bc5bf9a56e0c088  5363812c31bae08d549b36205b76dc87   
27   07d39c9c43a03208a3329192bfa03a01  1edf4deb02241e161f8364b5f3ba3b06   
28   080be1fb261fa4104673e0388e5ed508  0c857d0fdb5599b8fc5cfa1c9ba71c76   
29   082fce44f8c254bf6dc2c4e7bae58467  c5a9f32a64e9a1599bf9475ca0e4fa9c   
30   08af4067af2ca727cee7d572c5af8763  e0db405a62c796b1ac439c778de5e2f1   
31   08c95eb831d93a76079d7e24a117db29  e0998bd9b9ddc78c925d8a815f18673a   
32   092c9316ae71b2fe43e526043f351967  92b48641632e617da2beb5e94004bfce   
33   0a19df098ca05e7b026022a068f216f4  98604f5822a62e29afd0aab27caba202   
34   0a2d230e2761d958999166488ce599fe  4bc5169a978e02f6549db28307152ffa   
35   0a3fc5d5da7f44df671fd0c914381077  9429db44939723fc952317ec592c11e8   
36   0a42cf907d8c09bedbf6e69ccf60b7f9  ab05384b69b568cd123d40c97b5922e3   
37   0ae2b2edee0a604c92ccf6ed3c64376c  dea3bbce56fc4ca0aae5b3bdb784815b   
38   0b6ed326f1c69e74848157dc00027c91  7b47476bd22d79e6c7989cde5164b31c   
39   0b82ef8137cfb5f47ebcc41131c03663  334099ce6fb2daf71f1077d6442eb9a5   
40   0bdaf62bf3211420cb25a16386b56801  bf77f7e1f3be1c38f6686194ad96365a   
41   0be97ebc9313a86e02d3b7cdd7e5f1a6  f2d12fb9cdae4493f4349e9d65a66bba   
42   0c03bb1318921424fbd501cf9072bf89  fe4a1cf1ccfff5726ea94d79f2ef51ae   
43   0c2473e5a7533f687f8e6aa29efbdc7d  102592d98b12c6656e777e602d0b4474   
44   0c305f688ce08dc9402a2164fd6f29d6  f68cbab6cbaab1d6226e2dafed486578   
45   0c3f7c99a73c83fdf43aa51186a7b012  656d4ae23fefb8f2a2d6601c0f8f989a   
46   0c8fca0ebf003ce1352d04675da28d70  92b254d8ea10b8b91587f05411c648ae   
47   0cea363db5a2d424a276ed967b12b062  765f221989ff852ef0101e145946ad2a   
48   0cfcefc0ed0af6a2e601540feeac24e7  77cbda5b2227fa2e9de95536462fd31a   
49   0d07d0a588caf93cc66b7a8aff86d2fe  0f75924cbbe60142068f4029d744b724   
50   0dac48fbbab7c46ad058c8be85977e84  f5f97fb8cf2cf88369faede2ef900aca   
51   0dad07848c618cc5a4679a1bfe1db8d2  ec979208947bbba310f2ad8e50963725   
52   0db624494bc34733faf2f68bc0384e0d  688d5274462f

In [17]:
# Check if missing order_delivered_carrier_date is associated with seller_state
q = """

SELECT 
    seller_state,
    order_delivered_carrier_date,
    order_delivered_customer_date,
    COUNT(distinct order_id) AS cnt
FROM df
GROUP BY 1,2,3
HAVING order_delivered_carrier_date IS NULL
ORDER BY cnt DESC
"""
ps.sqldf(q, locals())


seller_state order_delivered_carrier_date order_delivered_customer_date  \
0            SP                         None                          None   
1            MG                         None                          None   
2            PR                         None                          None   
3            RJ                         None                          None   
4            SC                         None                          None   
5            RS                         None                          None   
6            BA                         None                          None   
7            DF                         None                          None   
8            GO                         None                          None   
9            ES                         None                          None   
10           AC                         None                          None   
11           CE                         None                          None   
12           PE                         None                          None   
13           PR                         None           2017-11-20 19:44:47   

    cnt  
0   650  
1    82  
2    79  
3    67  
4    29  
5    18  
6    14  
7     9  
8     5  
9     3  
10    1  
11    1  
12    1  
13    1

**Observation**:
- It seems the seller state affects the order_delivered_carrier_date
- Logically, if an item is not delivered it is possible that it is approved, cancelled or can be a pending order
- We can further investigate this with respect to order_status = 'delivered'

In [18]:
q = """

SELECT
    order_status,
    seller_state,
    order_delivered_carrier_date,
    COUNT(distinct order_id) AS cnt
FROM df
WHERE order_delivered_carrier_date IS NULL 
GROUP BY 1,2,3
    
"""
ps.sqldf(q, locals())

order_status seller_state order_delivered_carrier_date  cnt
0      approved           MG                         None    1
1      approved           SP                         None    1
2      canceled           BA                         None    2
3      canceled           DF                         None    3
4      canceled           GO                         None    3
5      canceled           MG                         None   40
6      canceled           PE                         None    1
7      canceled           PR                         None   21
8      canceled           RJ                         None   13
9      canceled           RS                         None    5
10     canceled           SC                         None   13
11     canceled           SP                         None  264
12    delivered           PR                         None    1
13    delivered           SP                         None    1
14     invoiced           BA                         None    7
15     invoiced           DF                         None    5
16     invoiced           MG                         None   20
17     invoiced           PR                         None   32
18     invoiced           RJ                         None   11
19     invoiced           RS                         None    3
20     invoiced           SC                         None    5
21     invoiced           SP                         None  217
22   processing           AC                         None    1
23   processing           BA                         None    5
24   processing           DF                         None    1
25   processing           ES                         None    2
26   processing           GO                         None    2
27   processing           MG                         None   21
28   processing           PR                         None   26
29   processing           RJ                         None   41
30   processing           RS                         None   10
31   processing           SC                         None   10
32   processing           SP                         None  165
33  unavailable           CE                         None    1
34  unavailable           ES                         None    1
35  unavailable           RJ                         None    2
36  unavailable           SC                         None    1
37  unavailable           SP                         None    2

**Observation**:
- We see that the missing orders are primarily one that are approved, canceled, processing, invoiced or are simply unavailble
- There are only two entries where the missing order_delivered_carrier_date is not valid; for order_status being "delivered"
- This shows there is reasonable explanation to have null values in 'order_delivered_carrier_date'. Hence they are not missing at random. It would be beneficial to roughly estimate the two delivery dates based on other factors such as state of delivery, seller state and possibly the product category.

### Assessing missing values for `order_delivered_customer_date`

In [19]:
q = """

SELECT 
    order_status,
    order_delivered_customer_date,
    COUNT(DISTINCT order_id) AS missing_count
FROM df
WHERE order_delivered_customer_date IS NULL
GROUP BY 1,2
"""
ps.sqldf(q, locals())

order_status order_delivered_customer_date  missing_count
0     approved                          None              2
1     canceled                          None            422
2    delivered                          None              8
3     invoiced                          None            300
4   processing                          None            284
5      shipped                          None           1008
6  unavailable                          None              6

**Observation**:
- We notice that only 8 delivered orders have missing `order_delivered_customer_date`
- The rest of the missing values make sense as the status is not delivered
- Hence they are missing at random and can be imputed based on average delivery date, possibly based on product_category, seller_state and state of delivery


**Conclusion**: We will keep our missing values in the dataset as our analysis is not based on ML task which accounts for the missing values. Moreover, the missing values are negligible in numbers and we want our report to incorporate all the dates present in the dataset

### Feature Engineering of Dates

In [20]:
# Dataframe overview
df.head(10)

customer_id                customer_unique_id  \
0  00012a2ce6f8dcda20d059ce98491703  248ffe10d632bebe4f7267f1f44844c9   
1  000161a058600d5901f007fab4c27140  b0015e09bb4b6e47c52844fab5fb6638   
2  0001fd6190edaaf884bcaf3d49edf079  94b11d37cd61cb2994a194d11f89682b   
3  0002414f95344307404f0ace7a26f1d5  4893ad4ea28b2c5b3ddf4e82e79db9e6   
4  000379cdec625522490c315e70c7a9fb  0b83f73b19c2019e182fd552c048a22c   
5  0004164d20a9e969af783496f3408652  104bdb7e6a6cdceaa88c3ea5fa6b2b93   
6  000419c5494106c306a97b5635748086  14843983d4a159080f6afe4b7f346e7c   
7  00046a560d407e99b969756e0b10f282  0b5295fc9819d831f68eb0e9a3e13ab7   
8  00050bf6e01e69d5c0fd612f1bcfb69c  e3cf594a99e810f58af53ed4820f25e5   
9  000598caf2ef4117407665ac33275130  7e0516b486e92ed3f3afdd6d1276cfbd   

  customer_zip_code_prefix   customer_city customer_state  \
0                     6273          osasco             SP   
1                    35550     itapecerica             MG   
2                    29830    nova venecia             ES   
3                    39664        mendonca             MG   
4                     4841       sao paulo             SP   
5                    13272        valinhos             SP   
6                    24220         niteroi             RJ   
7                    20540  rio de janeiro             RJ   
8                    98700            ijui             RS   
9                    35540        oliveira             MG   

                           order_id                        product_id  \
0  5f79b5b0931d63f1a42989eb65b9da6e  64315bd8c0c47303179dd2e25b579d00   
1  a44895d095d7e0702b6a162fa2dbeced  84183944dc7cddca87a5d384452c1d3c   
2  316a104623542e4d75189bb372bc5f8d  9df2b21ec85378d71df4404712e17478   
3  5825ce2e88d5346438686b0bba99e5ee  af3ec22cce878225aae6d9eb6c7a78eb   
4  0ab7fb08086d4af9141453c91878ed7a  868b3136c5b206f91b8208fbfdf2cb7c   
5  cd3558a10d854487b4f907e9b326a4fc  fa23bf270fb9880690b07d09b9f9ff20   
6  07f6c3baf9ac86865b60f640c4f923c6  daa7499d1e545811c843e8189cd30286   
7  8c3d752c5c02227878fae49aeaddbfd7  ba9f160a6ae1c23f25d690fd06fe4fd8   
8  fa906f338cee30a984d0945b3832e431  79ad39409fa4bcc36b4b7f734c79c2a2   
9  9b961b894e797f63622137ff7eb1c1af  c53feca3e876804031ed4a4b48ac8f1e   

                          seller_id  shipping_limit_date    price  \
0  7aa4334be125fcdd2ba64b3180029f14  2017-11-21 16:35:32    89.80   
1  2a1348e9addc1af5aaa619b1a3679d6b  2017-07-20 09:55:12    54.90   
2  46dc3b2cc0980fb8ec44634e21d2718e  2017-03-06 11:15:20   179.99   
3  aafe36600ce604f205b86b5084d3d767  2017-08-23 03:10:27   149.90   
4  4a3ca9315b744ce9f8e9374361493884  2018-04-10 03:10:19    93.00   
5  1b8356dabde1d35e17cef975c3f82730  2017-04-18 08:50:12    59.99   
6  e5a3438891c0bfdb9394643f95273d8e  2018-03-08 14:10:38    34.30   
7  ac3508719a1d8f5b7614b798f70af136  2017-12-22 12:45:31   120.90   
8  1da3aeb70d7989d1e6d9b0e887f97c23  2017-09-21 16:15:13    69.99   
9  6c6cc59a5c00cacc5054ca06d65cc282  2018-08-21 12:25:08  1107.00   

                          review_id  review_score order_status  \
0  65645c124061b43b2edc38b05ee76aab             1    delivered   
1  862cae301754fcafa8129022c8eca937             4    delivered   
2  238e7cc8c4579a3d4db8f2a211db5b06             5    delivered   
3  c3a9be1f602ecba1c7bdff5639c975fe             5    delivered   
4  fab6aa1b4c382a27ae8625faa342c229             4    delivered   
5  2bf2913f793ffd3739c41cccfc43c8c5             1    delivered   
6  f72dc5627bd78fb840c136295ae345f5             1    delivered   
7  494c3989426b2271e20bbac41e6acf96             5    delivered   
8  d50791ccc55c7f5ff8fde67e7c3baf59             5    delivered   
9  f149a8ca142b2324fd2578f67eaacd4b             5    delivered   

  order_purchase_timestamp    order_approved_at order_delivered_carrier_date  \
0      2017-11-14 16:08:26  2017-11-14 16:35:32          2017-11-17 15:32:08   
1      2017-07-16 09:40:32  2017-07-16 09:55:12          2017-07-19 19:09:37   
2      2017-02-28

In [21]:
# Manipulating `order_purchase` timestamps:
order_purchase_at_date = df['order_purchase_timestamp'].str.split(" ", 1, expand=True)[0]
order_purchase_at_time = df['order_purchase_timestamp'].str.split(" ", 1, expand=True)[1]

df['order_purchase_date'] = order_purchase_at_date


In [22]:
# Manipulating `order_delivered_carrier` timestamps:
order_delivered_carrier_date = df['order_delivered_carrier_date'].str.split(" ", 1, expand = True)[0]
order_delivered_carrier_time = df['order_delivered_carrier_date'].str.split(" ", 1, expand = True)[1]

df.order_delivered_carrier_date = order_delivered_carrier_date

In [23]:
# Manipulating 'order_delivered_customer' timestamp
order_delivered_customer_date = df['order_delivered_customer_date'].str.split(" ", 1, expand = True)[0]
order_delivered_customer_time = df['order_delivered_customer_date'].str.split(" ", 1, expand = True)[1]

df.order_delivered_customer_date = order_delivered_carrier_date

In [24]:
# Manipulating 'order_approved_at_date' timestamp
order_approved_at_date=df.order_approved_at.str.split(' ', 1, expand=True)[0]
order_approved_at_time=df.order_approved_at.str.split(' ', 1, expand=True)[1]

df['order_approved_at_date']=order_approved_at_date

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100750 entries, 0 to 100749
Data columns (total 24 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   customer_id                    100750 non-null  object 
 1   customer_unique_id             100750 non-null  object 
 2   customer_zip_code_prefix       100750 non-null  object 
 3   customer_city                  100750 non-null  object 
 4   customer_state                 100750 non-null  object 
 5   order_id                       100750 non-null  object 
 6   product_id                     100750 non-null  object 
 7   seller_id                      100750 non-null  object 
 8   shipping_limit_date            100750 non-null  object 
 9   price                          100750 non-null  float64
 10  review_id                      100750 non-null  object 
 11  review_score                   100750 non-null  int64  
 12  order_status                  

**Summary of modifications for timestamps**:<br>
-> order_purchase_date: only date extracted<br>
-> order_delivered_carrier_date: only date extracted<br>
-> order_delivered_customer_date: only date extracted<br>
-> order_approved_at_date:  only date extracted

In [26]:
# Changing the datatype of these colums:
from datetime import datetime, timedelta


#change the type of the column to date
df.order_purchase_date=pd.to_datetime(df.order_purchase_date)
df.order_approved_at_date=pd.to_datetime(df.order_approved_at_date)


df.order_delivered_carrier_date=pd.to_datetime(df.order_delivered_carrier_date)
df.order_delivered_customer_date=pd.to_datetime(df.order_delivered_customer_date)

In [27]:
# Verifying change
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100750 entries, 0 to 100749
Data columns (total 24 columns):
 #   Column                         Non-Null Count   Dtype         
---  ------                         --------------   -----         
 0   customer_id                    100750 non-null  object        
 1   customer_unique_id             100750 non-null  object        
 2   customer_zip_code_prefix       100750 non-null  object        
 3   customer_city                  100750 non-null  object        
 4   customer_state                 100750 non-null  object        
 5   order_id                       100750 non-null  object        
 6   product_id                     100750 non-null  object        
 7   seller_id                      100750 non-null  object        
 8   shipping_limit_date            100750 non-null  object        
 9   price                          100750 non-null  float64       
 10  review_id                      100750 non-null  object        
 11  

# Beginning with our Analysis

* How much revenue did we make this week? 
* What was the w/w change in revenue?
* What was the y/y growth in revenue?

In [28]:
"""
Our latest date when the last order is approved will be the maximum date in our dataset 
when our order is approved

"""
max_report_date = max(df.order_approved_at_date)

print(max_report_date)

2018-09-03 00:00:00


In [29]:
# Calculating our financial week start and end dates
financial_week_end = max_report_date
financial_week_start = max_report_date - timedelta(days = 6)

# Calculating our previous financial week start and end dates
prev_financial_week_end = max_report_date - timedelta(days = 7)
prev_financial_week_start = prev_financial_week_end- timedelta(days = 6)

# Calculating our previous financial year's start and end dates
ly_financial_week_end = max_report_date - timedelta(days = 364)
ly_financial_week_start = ly_financial_week_end - timedelta(days = 6)

# Calculating our start and end dates, one week previous to our ly_financial_week_end
ly_prev_financial_week_end = ly_financial_week_end - timedelta(days = 7)
ly_prev_financial_week_start = ly_prev_financial_week_end - timedelta(days = 6)

In [30]:
print(financial_week_end)
print(financial_week_start)

2018-09-03 00:00:00
2018-08-28 00:00:00


In [32]:
# revenue this week and previous week:
revenue_tw = df[(df.order_approved_at_date <= financial_week_end) & (df.order_approved_at_date >= financial_week_start)].groupby('customer_state')['price'].sum()
revenue_lw = df[(df.order_approved_at_date <= prev_financial_week_end) & (df.order_approved_at_date >= prev_financial_week_start)].groupby('customer_state')['price'].sum()

# revenue this year(by week) and previous year(by week):
revenue_tw_ly = df[(df.order_approved_at_date <= ly_financial_week_end) & (df.order_approved_at_date >= ly_financial_week_start)].groupby('customer_state')['price'].sum()
revenue_lw_ly = df[(df.order_approved_at_date <= ly_prev_financial_week_end) & (df.order_approved_at_date >= ly_prev_financial_week_start)].groupby('customer_state')['price'].sum()

# number of products this week and previous week
orders_tw = df[(df.order_approved_at_date <= financial_week_end) & (df.order_approved_at_date >= financial_week_start)].groupby('customer_state')['order_id'].nunique()
orders_lw = df[(df.order_approved_at_date <= prev_financial_week_end) & (df.order_approved_at_date >= prev_financial_week_start )].groupby('customer_state')['order_id'].nunique()

# Number of products this year(by week) and previous year(by week)
orders_tw_ly = df[(df.order_approved_at_date <= ly_financial_week_end) & (df.order_approved_at_date >= ly_financial_week_start)].groupby('customer_state')['order_id'].nunique()
orders_lw_ly = df[(df.order_approved_at_date <= ly_prev_financial_week_end) & (df.order_approved_at_date >= ly_prev_financial_week_start)].groupby('customer_state')['order_id'].nunique()


In [34]:
# Dataframe for storing all the previous results
rev_df=pd.DataFrame([revenue_tw, revenue_lw,revenue_tw_ly,revenue_lw_ly,orders_tw,orders_lw,orders_tw_ly,orders_lw_ly]).transpose()
rev_df.columns=['revenue_tw','revenue_lw','revenue_tw_ly','revenue_lw_ly','orders_tw','orders_lw','orders_tw_ly','orders_lw_ly']

In [35]:
rev_df

revenue_tw  revenue_lw  revenue_tw_ly  revenue_lw_ly  \
customer_state                                                         
MG                   45.90    11766.26       18616.23       10611.65   
PR                  407.90     3594.04        4719.22        5531.70   
RJ                  182.90    10298.15       20314.62       12828.63   
RS                  116.50     3339.35        9299.56        6052.91   
SP                 5479.04    61025.39       57525.90       35506.95   
AC                     NaN      220.70        1394.99         276.14   
BA                     NaN      774.61        9847.49        3565.09   
CE                     NaN      755.90        3141.38        1823.58   
DF                     NaN     2272.54        5103.05        1860.32   
ES                     NaN     3363.18        3077.63        1968.91   
GO                     NaN     1043.68        3111.72        1981.94   
MA                     NaN      416.98        5113.09        1539.22   
MS                     NaN      239.48        1605.90         964.85   
MT                     NaN      262.19         719.77        1673.64   
PB                     NaN      549.80         679.89         242.80   
PE                     NaN      746.88        2311.13        2152.02   
PI                     NaN       65.00         402.89         616.90   
RN                     NaN       29.90         916.22         466.99   
SC                     NaN     2893.33        6381.92        4040.77   
AL                     NaN         NaN        4059.45         812.69   
PA                     NaN         NaN        2827.47        3491.54   
RO                     NaN         NaN        1798.50         194.87   
SE                     NaN         NaN        3236.67            NaN   
TO                     NaN         NaN        1200.00         181.89   
AM                     NaN         NaN            NaN         639.80   

                orders_tw  orders_lw  orders_tw_ly  orders_lw_ly  
customer_state                                                    
MG                    1.0      110.0         108.0          87.0  
PR                    3.0       46.0          46.0          37.0  
RJ                    4.0       98.0         134.0         107.0  
RS                    1.0       27.0          65.0          62.0  
SP                   63.0      591.0         350.0         335.0  
AC                    NaN        1.0           2.0           1.0  
BA                    NaN        6.0          36.0          34.0  
CE                    NaN        4.0          21.0          13.0  
DF                    NaN       22.0          22.0          19.0  
ES                    NaN       11.0          19.0          17.0  
GO                    NaN        9.0          25.0          15.0  
MA                    NaN        3.0          16.0           8.0  
MS                    NaN        3.0           3.0           7.0  
MT                    NaN        2.0           6.0          12.0  
PB                    NaN        3.0           3.0           4.0  
PE                    NaN        5.0          14.0          20.0  
PI                    NaN        1.0           3.0           4.0  
RN                    NaN        1.0           6.0           3.0  
SC                    NaN       21.0          40.0          30.0  
AL                    NaN        NaN           7.0           3.0  
PA                    NaN        NaN           8.0          15.0  
RO                    NaN        NaN           7.0           4.0  
SE                    NaN        NaN          10.0           NaN  
TO                    NaN        NaN           1.0           4.0  
AM                    NaN        NaN           NaN           2.0

In [36]:
agg_rev_df = pd.DataFrame(rev_df.sum()).transpose()
agg_rev_df

revenue_tw  revenue_lw  revenue_tw_ly  revenue_lw_ly  orders_tw  orders_lw  \
0     6232.24   103657.36      167404.69        99025.8       72.0      964.0   

   orders_tw_ly  orders_lw_ly  
0         952.0         843.0

In [37]:
agg_rev_df['rev_w_w_change'] = agg_rev_df.revenue_tw/agg_rev_df.revenue_lw - 1
agg_rev_df['rev_y_y_change'] = agg_rev_df.revenue_tw/agg_rev_df.revenue_tw_ly - 1

agg_rev_df['orders_w_w_change'] = agg_rev_df.orders_tw/agg_rev_df.orders_lw - 1
agg_rev_df['orders_y_y_change'] = agg_rev_df.orders_tw/agg_rev_df.orders_tw_ly - 1

agg_rev_df

revenue_tw  revenue_lw  revenue_tw_ly  revenue_lw_ly  orders_tw  orders_lw  \
0     6232.24   103657.36      167404.69        99025.8       72.0      964.0   

   orders_tw_ly  orders_lw_ly  rev_w_w_change  rev_y_y_change  \
0         952.0         843.0       -0.939877       -0.962771   

   orders_w_w_change  orders_y_y_change  
0          -0.925311           -0.92437

In [64]:
# Creating our report values for Revenue
revenue_tw = round(agg_rev_df.revenue_tw[0], 2)
w_w_revenue_change = round(agg_rev_df.rev_w_w_change[0], 2)
y_y_revenue_change = round(agg_rev_df.rev_y_y_change[0], 2)

# Creating our report values for Orders
orders_tw = round(agg_rev_df.orders_tw[0], 2)
w_w_order_change = round(agg_rev_df.orders_w_w_change[0], 2)
y_y_order_change = round(agg_rev_df.orders_y_y_change[0], 2)


if w_w_revenue_change < 0:
    change ='decreased'
else:
    change = 'increased'

    
if y_y_revenue_change < 0:
    y_change ='decreased'
else:
    y_change = 'increased'
    

if w_w_order_change < 0:
    p_change ='decreased'
else:
    p_change = 'increased'

    
if y_y_order_change < 0:
    p_y_change ='decreased'
else:
    p_y_change = 'increased'


## What percentage of our sales target have we reached (QTD, and EoQ)?
- QTD: Quarter to date 
- EoQ: End of Quarter

**Assuming our quarter starts from July 1 2017, [`you can change this to your preference`]**

In [45]:
# Assumption: start of qaurter
quarter_start = '2018-07-01'

# to work this string type data we first convert it to datetime format:
format = '%Y-%m-%d'
quarter_start = datetime.strptime(quarter_start, format)
print(f'This year Quarter Starts On: {quarter_start}')

quarter_end = quarter_start + timedelta(days = 91)
print(f'This year Quarter Ends On: {quarter_end}')

quarter_start_ly = quarter_start - timedelta(days = 365)
print(f'\nLast year Quarter Started on: {quarter_start_ly}')

quarter_end_ly = quarter_end - timedelta(days = 365)
print(f'Last year Quarter Ended on: {quarter_end_ly}')

This year Quarter Starts On: 2018-07-01 00:00:00
This year Quarter Ends On: 2018-09-30 00:00:00

Last year Quarter Started on: 2017-07-01 00:00:00
Last year Quarter Ended on: 2017-09-30 00:00:00


> We can now compute and comapre our respective Revenues for this quarter and the quarter from last year

### End of Qaurter Revenue Details:

In [52]:
# Calculate revenue this quarter
revenue_this_q = df[(df.order_approved_at_date >= quarter_start) & (df.order_approved_at_date <= quarter_end)]['price'].sum()

# Calculate revenue for the same quarter last year
revenue_last_q = df[(df.order_approved_at_date >= quarter_start_ly) & (df.order_approved_at_date <= quarter_end_ly)]['price'].sum()

# Calculate the target for this quarter, which is last year's revenue plus 10%
target_tq = revenue_last_q * 1.1

# Difference between this quarter's revenue and the target revenue
difference = revenue_this_q - target_tq

# Print statements
print(f"Revenue for the current quarter (from {quarter_start} to {quarter_end}): ${revenue_this_q:,.2f}")
print(f"Revenue for the same quarter last year (from {quarter_start_ly} to {quarter_end_ly}): ${revenue_last_q:,.2f}")
print(f"Target revenue for this quarter (10% growth over last year): ${target_tq:,.2f}")
print(f"Difference between actual revenue this quarter and target: ${difference:,.2f}")

if difference > 0:
    print("We have surpassed the growth target for this quarter.")
else:
    print("We have not met the growth target for this quarter.")

Revenue for the current quarter (from 2018-07-01 00:00:00 to 2018-09-30 00:00:00): $1,636,111.69
Revenue for the same quarter last year (from 2017-07-01 00:00:00 to 2017-09-30 00:00:00): $1,555,998.73
Target revenue for this quarter (10% growth over last year): $1,711,598.60
Difference between actual revenue this quarter and target: $-75,486.91
We have not met the growth target for this quarter.


### Quarter to Date details:

In [55]:
# Calculate the number of days from the start of the quarter to the last report date
days_into_quarter = max_report_date - quarter_start

# Number of days in a full quarter - usually 90 or 91, depending on the specific quarter.
full_qaurter_days = 91

# QTD revenue = daily target in the quarter * days into qaurter
qtd_target = (target_tq/full_qaurter_days) * days_into_quarter.days

# Target acheviemen this quarter 
target_achievement_tq = (revenue_this_q/qtd_target)*100

print(f"Target Achievement QTD: {target_achievement_tq:.2f}%")
print(f"Days into Quarter: {days_into_quarter.days}")

Target Achievement QTD: 135.92%
Days into Quarter: 64


## Average ratings this week:

In [71]:
# Avg Ratings this week
avg_ratings = df[(df.order_approved_at_date <= financial_week_end)&(df.order_approved_at_date >= financial_week_start)]['review_score'].mean()

# Avg ratings last week
avg_ratings_ly = df[(df.order_approved_at_date <= prev_financial_week_end)&(df.order_approved_at_date >= prev_financial_week_start)]['review_score'].mean()

# Print statements
print(f"Average customer ratings for this week ({financial_week_start} to {financial_week_end}): {avg_ratings_tw:.2f} out of 5")
print(f"Average customer ratings for last week ({prev_financial_week_start} to {prev_financial_week_end}): {avg_ratings_ly:.2f} out of 5")

if  avg_ratings >= 4.8:
    status ='excellent'
elif avg_ratings >= 4.5:
    status = 'good'
else:
    status='poor'

Average customer ratings for this week (2018-08-28 00:00:00 to 2018-09-03 00:00:00): 4.31 out of 5
Average customer ratings for last week (2018-08-21 00:00:00 to 2018-08-27 00:00:00): 4.36 out of 5


## What was the average time it took for an order to be fullfilled and delivered this week and last week?

In [57]:
# Adding a colums delivery_days:
df['delivery_days'] = (df.order_delivered_carrier_date - df.order_purchase_date).dt.days
# Confirm change
df.head()

customer_id                customer_unique_id  \
0  00012a2ce6f8dcda20d059ce98491703  248ffe10d632bebe4f7267f1f44844c9   
1  000161a058600d5901f007fab4c27140  b0015e09bb4b6e47c52844fab5fb6638   
2  0001fd6190edaaf884bcaf3d49edf079  94b11d37cd61cb2994a194d11f89682b   
3  0002414f95344307404f0ace7a26f1d5  4893ad4ea28b2c5b3ddf4e82e79db9e6   
4  000379cdec625522490c315e70c7a9fb  0b83f73b19c2019e182fd552c048a22c   

  customer_zip_code_prefix customer_city customer_state  \
0                     6273        osasco             SP   
1                    35550   itapecerica             MG   
2                    29830  nova venecia             ES   
3                    39664      mendonca             MG   
4                     4841     sao paulo             SP   

                           order_id                        product_id  \
0  5f79b5b0931d63f1a42989eb65b9da6e  64315bd8c0c47303179dd2e25b579d00   
1  a44895d095d7e0702b6a162fa2dbeced  84183944dc7cddca87a5d384452c1d3c   
2  316a104623542e4d75189bb372bc5f8d  9df2b21ec85378d71df4404712e17478   
3  5825ce2e88d5346438686b0bba99e5ee  af3ec22cce878225aae6d9eb6c7a78eb   
4  0ab7fb08086d4af9141453c91878ed7a  868b3136c5b206f91b8208fbfdf2cb7c   

                          seller_id  shipping_limit_date   price  \
0  7aa4334be125fcdd2ba64b3180029f14  2017-11-21 16:35:32   89.80   
1  2a1348e9addc1af5aaa619b1a3679d6b  2017-07-20 09:55:12   54.90   
2  46dc3b2cc0980fb8ec44634e21d2718e  2017-03-06 11:15:20  179.99   
3  aafe36600ce604f205b86b5084d3d767  2017-08-23 03:10:27  149.90   
4  4a3ca9315b744ce9f8e9374361493884  2018-04-10 03:10:19   93.00   

                          review_id  review_score order_status  \
0  65645c124061b43b2edc38b05ee76aab             1    delivered   
1  862cae301754fcafa8129022c8eca937             4    delivered   
2  238e7cc8c4579a3d4db8f2a211db5b06             5    delivered   
3  c3a9be1f602ecba1c7bdff5639c975fe             5    delivered   
4  fab6aa1b4c382a27ae8625faa342c229             4    delivered   

  order_purchase_timestamp    order_approved_at order_delivered_carrier_date  \
0      2017-11-14 16:08:26  2017-11-14 16:35:32                   2017-11-17   
1      2017-07-16 09:40:32  2017-07-16 09:55:12                   2017-07-19   
2      2017-02-28 11:06:43  2017-02-28 11:15:20                   2017-03-01   
3      2017-08-16 13:09:20  2017-08-17 03:10:27                   2017-08-19   
4      2018-04-02 13:42:17  2018-04-04 03:10:19                   2018-04-04   

  order_delivered_customer_date seller_zip_code_prefix        seller_city  \
0                    2017-11-17                  18500  laranjal paulista   
1                    2017-07-19                  30494     belo horizonte   
2                    2017-03-01                  22240     rio de janeiro   
3                    2017-08-19                  88115           sao jose   
4                    2018-04-04                  14940           ibitinga   

  seller_state product_category_name_english payment_type order_purchase_date  \
0           SP                          toys  credit_card          2017-11-14   
1           MG                 health_beauty  credit_card          2017-07-16   
2           RJ                          baby  credit_card          2017-02-28   
3           SC                    cool_stuff       boleto          2017-08-16   
4           SP                bed_bath_table       boleto          2018-04-02   

  order_approved_at_date  delivery_days  
0             2017-11-14            3.0  
1             2017-07-16            3.0  
2             2017-02-28            1.0  
3             2017-08-17            3.0  
4             2018-04-04            2.0

In [59]:
# Calculating average time to deliver this week:
avg_delivery_time = df[(df.order_delivered_carrier_date <= financial_week_end)&(df.order_delivered_carrier_date >= financial_week_start)]['delivery_days'].mean()

# Calculating average time to deliver this week: [We dont need this in our report]
avg_delivery_time_lw=df[(df.order_delivered_carrier_date <= prev_financial_week_end )& (df.order_delivered_carrier_date >= prev_financial_week_start)]['delivery_days'].mean()


In [61]:
if  avg_delivery_time <= 1:
    status ='excellent'
elif avg_delivery_time <= 3:
    status = 'good'
else:
    status='poor'
    

In [73]:
print(f"""This week we generated {"${:0,.2f}".format(revenue_tw)} in revenue
      fulfilled {orders_tw.astype(str)} orders. Revenue {change} by 
      {w_w_revenue_change.astype(str)}% this week, y/y growth {y_change} by 
      {y_y_order_change}%. From a product perspective, sales {p_change} by 
      {w_w_order_change.astype(str)}%. this week, y/y growth {p_y_change} by
      {y_y_revenue_change.astype(str)}%
      
     QTD target achievement sits at {round(target_achievement_tq,2)}% and our EoQ target is {round(target_achievement_eoq,2)}% 
     
     Our ratings this week were {status} with an average rating of {avg_ratings}
     
     Our delivery times this week were {status} with an average delivery time of of {round(avg_delivery_time,2)}""")

This week we generated $6,232.24 in revenue
      fulfilled 72.0 orders. Revenue decreased by 
      -0.94% this week, y/y growth decreased by 
      -0.92%. From a product perspective, sales decreased by 
      -0.93%. this week, y/y growth decreased by
      -0.96%
      
     QTD target achievement sits at 135.92% and our EoQ target is 95.59% 
     
     Our ratings this week were poor with an average rating of 4.3108108108108105
     
     Our delivery times this week were poor with an average delivery time of of 3.73


## Executive Summary

This week at Olist, our automated report, leveraging the Brazilian E-commerce Public dataset, indicates fluctuations in our performance metrics. This report provides an in-depth analysis of our weekly revenues, customer satisfaction, and operational efficiency.

### Key Performance Indicators

- **Weekly Revenue**: This week, our total revenue amounted to **$6,232.24**.
- **Revenue by Region**: Details are segmented further in the attached detailed report.
- **Week-over-Week Change**: There was a slight decrease in revenue by **-0.94%**.
- **Year-over-Year Growth**: Revenue saw a decrease of **-0.92%** compared to the same week last year.
- **Sales Target Achievement**: 
  - **Quarter-to-Date (QTD)**: Achieved **135.92%** of the target.
  - **End of Quarter (EoQ)**: Currently at **95.59%** of the target.

### Customer Satisfaction

- **Average Customer Ratings**: This week, the average customer rating was **4.31**, which indicates satisfactory but not excellent performance.
- **Order Fulfillment and Delivery**:
  - **Orders Fulfilled**: A total of **72 orders** were processed this week.
  - **Average Delivery Time**: The average delivery time was **3.73 days**, indicating a need for improvement in delivery efficiency.

### Strategic Recommendations

1. **Enhance Delivery Efficiency**: Focus on reducing the average delivery time to improve customer satisfaction and repeat business.
2. **Monitor Revenue Fluctuations**: Investigate the causes of week-over-week and year-over-year declines in revenue and address them strategically.
3. **Capitalize on High QTD Achievement**: Leverage the momentum from exceeding QTD sales targets to ensure strong closure by the end of the quarter.

### Conclusion

In conclusion, while we are performing well against our sales targets, there are areas for improvement in customer satisfaction and delivery times. By addressing these issues, we can improve our service quality and sustain our revenue growth.

### Next Steps

- **Data-Driven Strategy Adjustment**: Use the insights from this report to refine our strategies, focusing on weak areas and bolstering our strengths.
- **Continuous Monitoring**: Keep a close watch on the weekly performance metrics to adapt quickly to any significant changes.

#### Note:
For detailed revenue analysis by region and further insights, refer to the full report attached. 

## Data Source

Data used for this report is sourced from the **Brazilian E-commerce Public dataset by Olist** available at: [Kaggle Olist Dataset](https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce?select=olist_sellers_dataset.csv).

